more cleanups

diff --git a/git-new b/git-new
--- a/git-new
+++ b/git-new
@@ -7,39 +7,39 @@ branch=$1
 git fetch -p
 
 if [[ $(current_branch) == "${branch}" ]]; then
-	writeln "<red>Error</red> Already checked out branch <yellow>${branch}</yellow>"
-	exit 1
+    writeln "<red>Error</red> Already checked out branch <yellow>${branch}</yellow>"
+    exit 1
 fi
 
 if [[ "${branch}" == "-" ]]; then
-	previous_branch=$(previous_branch)
+    previous_branch=$(previous_branch)
 
-	writeln "Switching back to branch <magenta>${previous_branch}</magenta>"
+    writeln "Switching back to branch <magenta>${previous_branch}</magenta>"
 
-	git checkout --quiet -
-	git pull -p
+    git checkout --quiet -
+    git pull -p
 
-	exit 0
+    exit 0
 fi
 
-# Does the branch already exist? If yes, switch to it
+# Does the branch already exist? If yes, switch to it
 if git show-ref --quiet "refs/heads/${branch}"; then
-	writeln "Checking out branch <magenta>${branch}</magenta>"
+    writeln "Checking out branch <magenta>${branch}</magenta>"
 
-	git checkout --quiet "${branch}"
-	git pull -p
+    git checkout --quiet "${branch}"
+    git pull -p
 
-	exit 0
+    exit 0
 fi
 
-# Does the branch exist in remote? If yes, switch to it
-if git show-branch "remotes/origin/${branch}" > /dev/null 2>&1; then
-	writeln "Checking out branch <magenta>${branch}</magenta>"
+# Does the branch exist in remote? If yes, switch to it
+if git show-branch "remotes/origin/${branch}" >/dev/null 2>&1; then
+    writeln "Checking out branch <magenta>${branch}</magenta>"
 
-	git checkout --quiet "${branch}"
-	git pull -p
+    git checkout --quiet "${branch}"
+    git pull -p
 
-	exit 0
+    exit 0
 fi
 
 # The branch doesn't exist so create it if wanted
@@ -47,9 +47,9 @@ write "Branch <yellow>${branch}</yellow> does not exist. Do you want to create i
 read -r answer
 
 if [[ "${answer}" != "y" ]]; then
-	echo "Aborted."
+    echo "Aborted."
 
-	exit 0
+    exit 0
 fi
 
 writeln "Creating branch <green>${branch}</green>"
